# Generated by Django 5.0.7 on 2024-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
